# Generated by Django 3.2.4 on 2021-06-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=80, verbose_name='Nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cuentaUsuario', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cuenta')),
                ('passUsuario', models.CharField(max_length=15, verbose_name='Password')),
                ('emailUsuario', models.CharField(max_length=50, verbose_name='email')),
                ('nomUsuario', models.CharField(max_length=50, verbose_name='Nombre')),
                ('celUsuario', models.CharField(max_length=50, verbose_name='Celular')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codProducto', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Codigo producto')),
                ('nomProducto', models.CharField(max_length=30, verbose_name='Nombre producto')),
                ('imagen', models.ImageField(default='sinfoto.png', upload_to='images/', verbose_name='Imagen producto')),
                ('imagen2', models.ImageField(default='sinfoto.png', null=True, upload_to='images/', verbose_name='Imagen producto2')),
                ('precioProducto', models.IntegerField(verbose_name='Precio Producto')),
                ('precioProductoCred', models.IntegerField(null=True, verbose_name='Precio Producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
        ),
    ]
