# Generated by Django 3.2.4 on 2021-06-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_producto_imagen2'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(default='sinfoto.png', null=True, upload_to='images/', verbose_name='Imagen producto2'),
        ),
    ]
