# Generated by Django 3.2.4 on 2021-06-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_imagen2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nomProducto',
            field=models.CharField(max_length=50, verbose_name='Nombre producto'),
        ),
    ]
